import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './footer/page'
import Header from './header/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next JS Test',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      <body className={`h-full`}>
        <div className='flex flex-col gap-4 justify-between h-full'>
          <Header />
          <div className='p-4 flex items-center justify-center w-full'>
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
